[package]
name = "sol_to_ink"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
convert_case = "0.5.0"
substring = "1.4.5"
regex = "1.5.6"