[package]
name = "sol_to_ink"
version = "0.2.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
convert_case = "0.5.0"
substring = "1.4.5"
quote = "1"
proc-macro2 = "1.0.40"
syn = "1.0.42"